# Generated by Django 4.2 on 2025-08-27 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_imported', models.BooleanField(default=False)),
                ('edit_count', models.IntegerField(default=0)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('last_edited_field', models.CharField(blank=True, max_length=100, null=True)),
                ('last_edit_detail', models.TextField(blank=True, null=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_todos', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added Task'), ('deleted', 'Deleted Task'), ('completed', 'Completed Task'), ('edited', 'Edited Task'), ('imported', 'Imported Tasks'), ('exported', 'Exported Tasks')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
