# Generated by Django 4.2 on 2025-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='last_edit_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='last_edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='last_edited_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
