# Generated by Django 4.2 on 2025-08-28 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_count', models.IntegerField(default=0)),
                ('deleted_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('edited_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('export_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
