# Generated by Django 4.2 on 2025-08-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_userstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
