# Generated by Django 4.2 on 2025-08-24 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_todo_edit_count_todo_last_edit_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
