# Generated by Django 4.2 on 2025-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
